#!/bin/bash

./poornames    /usr/bin   > bin.1     2> bin.2
echo "Finished bin"
./poornames -r /usr/bin   > bin-r.1   2> bin-r.2
echo "Finished bin-r"

./poornames    /usr/lib   > lib.1     2> lib.2
echo "Finished lib"
./poornames -r /usr/lib   > lib-r.1   2> lib-r.2
echo "Finished lib-r"

./poornames    /usr/share > share.1   2> share.2
echo "Finished share"
./poornames -r /usr/share > share-r.1 2> share-r.2
echo "Finished share-r"
